Add dashboard in consumer HTTPServer
NicolasLM/sauna pull request #62
Opened 2017-03-09 23:12 UTC by bewiwi

Dashboard color is not really great but it works :D

2017-03-10 08:56 UTC, NicolasLM requested changes
I never thought about it and I like it. I was expecting it pink but...

I wonder if it shouldn't be a separate consumer. There are many improvements this dashboard could get in the future (sorting, filtering, night mode...). By separating it from the start we could be sure to modify it without breaking the JSON API that people already use to automate stuff.

It could depend on Jinja for example to prevent the XSS.

2017-03-10 08:56 UTC, NicolasLM commented on sauna/consumers/ext/http_server/__init__.py
> +        self.logging('debug', 'Exited consumer thread')
Shouldn't it be `self.logger` here?

2017-03-10 08:56 UTC, NicolasLM commented on sauna/consumers/ext/http_server/html.py
> +<head>
Could you use HTML5 and define the encoding as UTF-8? I get `Temperature okay (46Â°C)`.

2017-03-10 08:56 UTC, NicolasLM commented on sauna/consumers/ext/http_server/html.py
> +                       "</td><td>{}</td>" \
This is nice and simple but it leads to XSS:

```
  - type: Dummy
    checks:
      - type: dummy
        status: 0
        output: <script>alert('Hello')</script>
```

2017-03-13 18:02 UTC, bewiwi commented
I start to dev a different consumer, but i had duplicate lot of code. My goal was to have a simple dashboard without additional dependencies.

Maybe i can try to facto HTTP code but consumer will not be totally independent.  What do you think ?

2017-03-13 19:04 UTC, bewiwi commented on sauna/consumers/ext/http_server/html.py
> +                       "</td><td>{}</td>" \
fixed without jinja

2017-03-13 20:56 UTC, NicolasLM commented
Yes, if you can factorize code between the JSON API and the dashboard it would be great. If not then no problem, just fix the tests, address this encoding issue and we are good to merge.

2017-03-17 19:39 UTC, bewiwi commented
I can't reproduce test fail on my laptop, every test is OK. Can you try to run test on yours ?

2017-03-17 20:25 UTC, NicolasLM commented on sauna/consumers/ext/http_server/html.py
> +    file = open(path, 'r')
Use a context manager to avoid potentially leaking a file descriptor.

2017-03-17 20:42 UTC, NicolasLM commented on sauna/consumers/ext/http_server/dashboard.html.template
> +<html>
Insert `<!DOCTYPE html>`

2017-03-17 20:43 UTC, NicolasLM commented on sauna/consumers/ext/http_server/dashboard.html.template
> +<title>Sauna status</title>
Add `<meta charset="UTF-8">` as it still doesn't show my unicode snowman.

2017-03-17 21:00 UTC, NicolasLM commented on sauna/consumers/ext/http_server/dashboard.html.template
> +</html>
The file is not included in the distribution. You can either add it or just use the template as a string in a module, I don't mind it.

http://python-packaging.readthedocs.io/en/latest/non-code-files.html

2017-03-17 21:01 UTC, NicolasLM commented
Works on my laptop too. I made a few other comments, let me know when they are addressed and I will merge it.

2017-03-17 21:02 UTC, NicolasLM commented on sauna/consumers/ext/http_server/__init__.py
> +        # HTTP Server that exposes sauna status as a REST API
```
# HTTP Server that exposes sauna status as a REST API or a web dashboard
```

2017-03-21 15:09 UTC, merged